### ISSUE TITLE
【Enhancement-shortcut】window版的快捷键图标展示需要优化，应该不同于mac版

### ISSUE THREAD

**Issue by Sandu1213** [biyidev/biyi_app#13]
### Reproduce：

**Pre-condition:**
  - OS Version: Win10 专业版 (19042.1237)
  - App version: biyi v0.3.1

**Attchments:**
    ![OG1T7`O2 SICX(GM3P99@U3](https://user-images.githubusercontent.com/21214285/136923413-ea3d2966-0662-41a5-b88b-27d5ce2f1e81.png)

**Comment by lijy91** [comment]
Fixed and will be released in the next version.
