### ISSUE TITLE
【Enhancement-Text Translation Engine】显示语言设置为中文时，风格建议统一，不要出现多余英文

### ISSUE THREAD

**Issue by Sandu1213** [biyidev/biyi_app#14]
### Reproduce：

**Pre-condition:**
  - OS Version: Win10 专业版 (19042.1237)
  - App version: biyi v0.3.1

**Attchments:**
![image](https://user-images.githubusercontent.com/21214285/136925344-a6911993-31c3-4ae8-b3c3-c0012b766cf7.png)

**Comment by lijy91** [comment]
Fixed and will be released in the next version.
