### ISSUE TITLE
【Bug-Theme Mode】调整主题风格后，风格变了，显示的值未变

### ISSUE THREAD

**Issue by Sandu1213** [biyidev/biyi_app#18]
### Reproduce：

**Pre-condition:**
  - OS Version: Win10 专业版 (19042.1237)
  - App version: biyi v0.3.1

**Attchments:**

https://user-images.githubusercontent.com/21214285/136931534-787e2124-234e-41a9-b83c-44772b7e2c0c.mp4

**Comment by lijy91** [comment]
Fixed and will be released in the next version.
