### ISSUE TITLE
【Bug-exit】出现无法退出应用的情况（非必现）

### ISSUE THREAD

**Issue by Sandu1213** [biyidev/biyi_app#19]
### Reproduce：

**Pre-condition:**
  - OS Version: Win10 专业版 (19042.1237)
  - App version: biyi v0.3.1

**Attchments:** 

https://user-images.githubusercontent.com/21214285/136932068-1ac7082a-c3ab-4df1-91b8-eeca0df638fc.mp4

**Comment by lijy91** [comment]
已修复，将在下一版本中发布。
