### ISSUE TITLE
mac home 下的 biyi文件夹 前面加上.  变成隐藏文件夹

### ISSUE THREAD

**Issue by 24** [biyidev/biyi_app#27]
~/.biyi   这样

好处是:
1. 其他很多软件也是这样的 .+软件 , 
2. 隐藏起来, 干净整洁

**Comment by lijy91** [comment]
https://github.com/biyidev/pro_account_noop/commit/117073ce1563000b4101eb8438a034be8a786c9d

**Comment by lijy91** [comment]
Fixed and will be released in the next version.
