### ISSUE TITLE
Windows下没有窗口置顶时，截屏取词完不能自动弹出翻译窗口

### ISSUE THREAD

**Issue by RichardYann** [biyidev/biyi_app#28]
既然设置了屏幕取词的快捷键，那自然是希望在窗口没有打开的时候快速调用。但现在Windows下，若没有打开并置顶窗口，则截屏完不能弹出翻译，那这个快捷键也就没有意义了

**Comment by RichardYann** [comment]
刚看到之前有提过这个问题，说可能是因为没取到值？我觉得即便没取到值，也应该跳出窗口给个“未检测到目标”之类的反馈，这样会更友好些

**Comment by lijy91** [comment]
这个问题大概率是bug引起的，后续处理一下。

**Comment by lijy91** [comment]
已修改，将在下一版本中发布。
