### ISSUE TITLE
macOS 10.14.6无法使用

### ISSUE THREAD

**Issue by zhangmiaocc** [biyidev/biyi_app#29]
![vkkrlMEI0G](https://user-images.githubusercontent.com/4081078/141399432-cfda9bc1-c2f3-4de3-8f7e-ffc6da84af4c.png)

**Comment by lijy91** [comment]
已支持，将在下一版本中发布。

https://github.com/biyidev/biyi_app/commit/3294f075be59350b8aa41d45c8c7ed221ae3d883
