### ISSUE TITLE
Bug，Windows下点击【设置】按钮，会隐藏到后台

### ISSUE THREAD

**Issue by shiyuenianwu** [biyidev/biyi_app#30]
![image](https://user-images.githubusercontent.com/26448923/141740544-ac6a4617-68cc-42c3-bc47-b747b9300b8e.png)
![image](https://user-images.githubusercontent.com/26448923/141740621-ba93baf1-20e9-406e-ba05-28047d74ba8e.png)

**Comment by shiyuenianwu** [comment]
![image](https://user-images.githubusercontent.com/26448923/141740735-61035558-ed7b-4c02-8bec-47039c5bd23e.png)
bj版本号

**Comment by AptX395** [comment]
@lijy91 您好！非常感谢您开发的比译，我认为是一个非常精美的软件。不过我也遇到了上述 bug，并且是百分之百出现的，希望能够尽快修复呢~

**Comment by lijy91** [comment]
> @lijy91 您好！非常感谢您开发的比译，我认为是一个非常精美的软件。不过我也遇到了上述 bug，并且是百分之百出现的，希望能够尽快修复呢~

我会尽快修复该bug，临时解决方案是设置置顶后进入设置

**Comment by lijy91** [comment]
已修复，将在下一版本中发布。

https://github.com/biyidev/biyi_app/commit/8ff86f3b91e4ef202abd50ab8a631b1a5c81aa33
https://github.com/leanflutter/launch_at_startup/commit/87643efacf7b8122fd9053b49a0e52a4552792d6
