### ISSUE TITLE
记忆上一次窗口位置

### ISSUE THREAD

**Issue by lifesign** [biyidev/biyi_app#33]
测试发现当前的窗口出现位置是跟随托盘位置走的，那么当顶部菜单栏很满的情况下，始终会出现在最左侧，体验不太好，由于现在可以拖拽窗口，可以考虑让用户自行拖拽窗口到合适的位置，然后呼出的时候就是以这个位置出现，即记忆上一次的位置即可

**Comment by lijy91** [comment]
已修改，将在下一版本中发布。

> 在 macOS 系统中，点击托盘图标时主窗口将默认显示在图标下方。
