### ISSUE TITLE
libtray_manager_plugin.so: undefined symbol: uuid_generate

### ISSUE THREAD

**Issue by everyx** [biyidev/biyi_app#42]
你好，我想在 Arch 下使用，用 release 的 deb 包转换安装后提示

`/usr/lib/biyi_app/biyi: symbol lookup error: /usr/lib/biyi_app/lib/libtray_manager_plugin.so: undefined symbol: uuid_generate`

是需要安装什么依赖么？

**Comment by lijy91** [comment]
等下个版本，这个依赖已经移除

**Comment by everyx** [comment]
嗯嗯，已经可以了
