### ISSUE TITLE
macOS中esc键失灵

### ISSUE THREAD

**Issue by PentaTea** [biyidev/biyi_app#44]
比译版本: v0.3.4 (BUILD 7)
macOS BigSur 11.1
macbook pro 15-inch 2019

### 开启比译前:
- esc键正常
### 开启比译后:
- 无法触发包括vscode,截图工具,vim等esc键的功能
- 按键测试工具中按下esc键检测不到
- 按键测试工具中按下shift+esc键可以成功检测到shift和esc
- option+command+esc可以正常呼出强制关闭
- 打开比译弹窗后按下esc可以正常关闭
- 钉住比译弹窗后转移焦点到其他程序后按下esc也会关闭比译
- 将设置>键盘快捷键>隐藏 设为其他按键如`1`后,上述情况就换成1了

### 推测:
- 可能全局拦截了快捷按键

### 期望:
- 开启比译后可以正常使用esc键

**Comment by lijy91** [comment]
下一版本将修复，临时解决方案是先将隐藏窗口快捷键修改为其他快捷键

**Comment by PentaTea** [comment]
点击 设置>键盘快捷键>隐藏 后的弹窗也默认是esc键关闭
就导致无法成功设置快捷键为esc,点击后直接就关闭了

**Comment by walt1012** [comment]
windows11下出现同样问题，会影响到idea，微信等软件的esc键功能

**Comment by lijy91** [comment]
已修复
