### ISSUE TITLE
请问这个软件不能翻译西语吗？ 西语-中文，西语-英文都不行。

### ISSUE THREAD

**Issue by richfuns** [biyidev/biyi_app#50]
使用的是Mac版本 biyi-0.3.5 8-macos

<img width="407" alt="iShot2021-12-19 23 39 45" src="https://user-images.githubusercontent.com/1400999/146712977-17e8564d-e477-4598-8ce4-c2a99a9d736f.png">

**Comment by lijy91** [comment]
有一些引擎应该支持，但是看截图你没有配置相应的key.

**Comment by richfuns** [comment]
> 有一些引擎应该支持，但是看截图你没有配置相应的key

谢谢，的确有点麻烦，默认的引擎原来不能直接使用
