### ISSUE TITLE
打开一次应用，桌面右下角就会多一个快捷小图标，并且左键点击选择“显示”无反应

### ISSUE THREAD

**Issue by changjl317** [biyidev/biyi_app#6]
![4c735a9bea2b530cb78426e207f8261](https://user-images.githubusercontent.com/72779361/134851358-996d664d-8f17-4fb5-9356-f0e668485750.png)
![c24c0c29bc04ab64e8f5b9e6aa05ab7](https://user-images.githubusercontent.com/72779361/134851479-d2b8c2bd-12fb-47c5-9e04-9547256b78e4.png)

**Comment by lijy91** [comment]
该 Issue已修复，请更新到 `v0.3.1`。

https://github.com/biyidev/biyi_app/releases/tag/v0.3.1
