### ISSUE TITLE
Translation results overflowing the screen

### ISSUE THREAD

**Issue by zu1k** [biyidev/biyi_app#8]
If there are too many translation results, the window will expand downwards and the content will overflow beyond the visible area.

I suggest adding vertical scrollbars and adapting the window width against the length of the content to make more content visible.

<details>
<summary>Click to see picture</summary>

![pic](https://user-images.githubusercontent.com/42370281/135019815-ce46e0d0-908f-4b73-8a29-4b88a5e8d735.png)
</details>

**Comment by lijy91** [comment]
该 Issue已修复，请更新到 `v0.3.1`。

https://github.com/biyidev/biyi_app/releases/tag/v0.3.1
