### ISSUE TITLE
打开设置后，无法拖动窗口（可做优化）

### ISSUE THREAD

**Issue by changjl317** [biyidev/biyi_app#9]
![dae5915d0adca88885f823c6ea4e765](https://user-images.githubusercontent.com/72779361/135184474-e6ca7a41-ecaa-4c28-b202-97020cd4e868.png)

**Comment by lijy91** [comment]
该 Issue已修复，请更新到 `v0.3.1`。

https://github.com/biyidev/biyi_app/releases/tag/v0.3.1
